<a href="https://colab.research.google.com/github/CameronChadwick/data_analysis/blob/main/Moneyball.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
from matplotlib import pyplot as plt
import numpy as np 
import pandas as pd

# Files

In [69]:
pitch_raw = 'https://raw.githubusercontent.com/bobg207/Honors_Data_Analysis/master/2018_MLB_Pitching_Stats_II.txt'
hit_raw = 'https://raw.githubusercontent.com/bobg207/Honors_Data_Analysis/master/2018_MLB_Hitting_Stats.txt'
pitch_data = pd.read_csv(pitch_raw, delim_whitespace=True)
hit_data = pd.read_csv(hit_raw, delim_whitespace=True)

hit_data

,#,Team,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,SO,BB,AVG,OBP,SLG,OPS,WPCT
0,1,Indians_Cleveland,162,6300,5595,818,1447,297,19,216,786,135,36,1189,522,0.259,0.332,0.434,0.766,0.562
1,2,Rays_Tampa_Bay,162,6195,5475,716,1415,274,43,150,664,128,51,1388,523,0.258,0.333,0.406,0.739,0.556
2,3,Red_Sox_Boston,162,6302,5623,876,1509,355,31,208,829,125,31,1253,531,0.268,0.339,0.453,0.792,0.667
3,4,Brewers_Milwaukee,163,6210,5542,754,1398,252,24,218,711,124,32,1458,505,0.252,0.323,0.424,0.747,0.589
4,5,Nationals_Washington,162,6288,5517,771,1402,284,25,191,737,119,33,1289,575,0.254,0.335,0.419,0.754,0.506
5,6,Royals_Kansas_City,162,6063,5505,638,1350,283,29,155,606,117,38,1310,414,0.245,0.305,0.392,0.697,0.358
6,7,White_Sox_Chicago,162,6071,5523,656,1332,259,40,182,639,98,41,1594,407,0.241,0.302,0.401,0.703,0.383
7,8,Padres_San_Diego,162,6059,5486,617,1289,250,30,162,583,95,36,1523,443,0.235,0.297,0.380,0.677,0.407
8,8,Rockies_Colorado,163,6178,5541,780,1418,280,42,210,748,95,33,1397,469,0.256,0.322,0.435,0.757,0.558
9,10,Braves_Atlanta,162,6251,5582,759,1433,314,29,175,717,90,36,1290,458,0.257,0.324,0.417,0.741,0.556
10,11,Angels_Los_Angeles,162,6108,5472,721,1323,249,23,214,690,89,22,1300,476,0.242,0.313,0.413,0.726,0.494
11,12,Orioles_Baltimore,162,6034,5507,622,1317,242,15,188,593,81,22,1412,403,0.239,0.298,0.391,0.689,0.290
12,13,Mariners_Seattle,162,6087,5513,677,1402,256,32,176,644,79,37,1221,413,0.254,0.314,0.408,0.722,0.549
13,13,Dbacks_Arizona,162,6157,5460,693,1283,259,50,176,658,79,25,1460,524,0.235,0.310,0.397,0.707,0.506
14,15,Giants_San_Fran,162,6112,5541,603,1324,255,30,133,573,77,34,1467,408,0.239,0.300,0.368,0.668,0.451
15,15,Reds_Cincinnati,162,6240,5532,696,1404,251,25,172,665,77,33,1376,524,0.254,0.328,0.401,0.729,0.414
16,17,Dodgers_Los_Angeles,163,6358,5572,804,1394,296,33,235,756,75,24,1436,600,0.250,0.333,0.442,0.775,0.564
17,18,Rangers_Texas,162,6163,5453,737,1308,266,24,194,696,74,35,1484,539,0.240,0.318,0.404,0.722,0.414
18,19,Astros_Houston,162,6146,5453,797,1390,278,18,205,763,71,26,1197,546,0.255,0.329,0.425,0.754,0.636
19,19,Mets_New_York,162,6177,5468,676,1282,265,34,170,649,71,39,1404,530,0.234,0.312,0.389,0.701,0.475
20,21,Tigers_Detroit,162,6029,5494,630,1326,284,35,135,597,70,30,1341,410,0.241,0.300,0.380,0.680,0.395
21,21,Pirates_Pittsburgh,161,6066,5447,692,1381,290,38,157,665,70,38,1229,436,0.254,0.317,0.407,0.724,0.509
22,23,Phils_Philadelphia,162,6136,5424,677,1270,241,30,186,653,69,26,1520,549,0.234,0.314,0.393,0.707,0.494
23,24,Cubs_Chicago,163,6369,5624,761,1453,286,34,167,722,66,38,1388,509,0.258,0.333,0.410,0.743,0.583
24,25,Yankees_New_York,162,6271,5515,851,1374,269,23,267,821,63,21,1421,604,0.249,0.329,0.451,0.780,0.617
25,25,Cardinals_St._Louis,162,6200,5498,759,1369,248,9,205,725,63,32,1380,485,0.249,0.321,0.409,0.730,0.543
26,27,Blue_Jays_Toronto,162,6076,5477,709,1336,320,16,217,680,47,30,1387,484,0.244,0.312,0.427,0.739,0.451
27,27,Twins_Minnesota,162,6154,5526,738,1379,317,22,166,704,47,27,1328,509,0.250,0.318,0.405,0.723,0.481
28,29,Marlins_Miami,161,6083,5488,589,1303,222,24,128,554,45,31,1384,429,0.237,0.303,0.357,0.660,0.391
29,30,Athletics_Oakland,162,6255,5579,813,1407,322,20,227,778,35,21,1381,532,0.252,0.325,0.439,0.764,0.599

# Moneyball

In [70]:
def correlation(x, y):
  x_sum = 0
  x_squ = 0
  y_sum = 0
  y_squ = 0
  xy_sum = 0

  for n in range(len(x)):
    xy_sum += x[n] * y[n]
    x_sum += x[n]
    x_squ += x[n] * x[n]
    y_sum += y[n]
    y_squ += y[n] * y[n]

  x_y = x_sum * y_sum
  numerator = len(x) * xy_sum - x_y

  subtract_x = (len(x) * x_squ - x_sum**2)**0.5
  subtract_y = (len(y) * y_squ - y_sum**2)**0.5
  denomonator = subtract_x * subtract_y
  corr_coeff = numerator / denomonator
  return corr_coeff

hit_columns = ['WPCT', 'OBP', 'SLG', 'AVG', 'RBI']
pitch_columns = ['WPCT', 'ERA', 'SO', 'ER', 'HR']
hit_corrs = []
pitch_corrs = []
for index in range(1, len(hit_columns)):
  hit_corr = correlation(hit_data[hit_columns[0]], hit_data[hit_columns[index]])
  hit_corrs.append(hit_corr)
  pitch_corr = correlation(pitch_data[pitch_columns[0]], pitch_data[pitch_columns[index]])
  pitch_corrs.append(pitch_corr)

print(hit_corrs)
print(pitch_corrs)

[0.7983428839608936, 0.7498257778361505, 0.6885904560640973, 0.823533143822496]
[-0.8757967641592198, 0.7361970808267791, -0.8748084994941681, -0.6566336239528022]